### ISSUE TITLE
Unexpected token: ';'

### ISSUE THREAD

**Issue by emilos** [buxlabs/boxwood#657]
Seems to work correctly, but shows an error in the console:

```html
<style>
  div[class*="status-"]::after {
    content: "";
    display: block;
    position: absolute;
    width: 100%;
    height: 100%;
    background-repeat:  no-repeat;
    background-position: bottom center;
    background-size: contain;
    opacity: 0.1;
  }
  .status-400::after {
    background-image: url('/assets/images/400.svg');
  }
  .status-401::after {
    background-image: url('/assets/images/401.svg');
  }
  .status-403::after {
    background-image: url('/assets/images/403.svg');
  }
  .status-404::after {
    background-image: url('/assets/images/404.svg');
  }
  .status-500::after {
    background-image: url('/assets/images/500.svg');
  }
</style>

```

**Comment by inikonorov** [comment]
can you share what version of node do you test? I use 14.11.0 - everything is ok (screen below).
![image](https://user-images.githubusercontent.com/30556799/99303973-915be180-2873-11eb-8f5d-0313077899e7.png)

**Comment by inikonorov** [comment]
hey, can you comment this?)

**Comment by emilos** [comment]
@inikonorov I'm trying to reproduce this again, but without much luck :) going to try again now.

**Comment by emilos** [comment]
@inikonorov ok, I've found it. I've added a skipped spec here https://github.com/buxlabs/boxwood/commit/c1e570d4cb8105f517cee57f3c442dc2b9156231 if you want to have a look :) thanks!

**Comment by inikonorov** [comment]
I play with code and found something
I think, that problem is if-condition (35-37 rows) in `prerun` function in `plugins/DataPlugin.js`
I made some tests:

- 1 test (current if-condition and template from `c1e570d` commit
![image](https://user-images.githubusercontent.com/30556799/100135679-cbe50000-2eab-11eb-9b48-cf9c2eb7cb69.png)

- 2 test (current if-condition and my template based on template from 1st test
![image](https://user-images.githubusercontent.com/30556799/100135818-fdf66200-2eab-11eb-898b-1b34ee79e79f.png)

- 3 test (changed if-condition and template from 1st test)
![image](https://user-images.githubusercontent.com/30556799/100135932-254d2f00-2eac-11eb-901e-b0f6568753e6.png)

I think, that when `optimizeNode` function finds curly brackets in style tag, she thinks that in curly brackets there is some JS code. So 2nd test works correctly, because in curly brackets there is a real JS code.
I don't know is 3rd test's if-condition right and I can do pull request with this solution, so I wait your opinion about this :)

**Comment by emilos** [comment]
@inikonorov this makes a lot of sense, good find! This seems to be a wider problem, I think same issue would happen if we would have a `script` tag defined with something inside of it (or any other tag that can take in code).

I think the right solution for this, is to do something like this inside of the `DataPlugin`

```js
const CODE_TAGS = ['style', 'script']

// ...

if (CODE_TAGS.includes(tag)) {
   fragment.children.forEach(node => {
     node.skipDataOptimization = true
   })
}

// ...

if (this.variables.length > 0 && !fragment.skipDataOptimization) {
  // ...
}
```

**Comment by inikonorov** [comment]
okay, 'll do this today :)

**Comment by inikonorov** [comment]
https://github.com/buxlabs/boxwood/pull/667
