### ISSUE TITLE
Can I use it at Client-side, for example: click to change somethings?

### ISSUE THREAD

**Issue by htdangkhoa** [buxlabs/boxwood#698]

**Comment by emilos** [comment]
Hey @htdangkhoa,

I'll try to describe a bigger picture first, so whoever comes here can read it as well :). The intention of the engine is to be used server side to render html for the browser. The goal here is to use as little js client side as possible (ideally zero), so that the rendered page is fast on a variety of devices and does not do any interpretation in the browser. This might not be a goal for all apps, you might want to build something that's client side heavy, and in that case boxwood is most likely not for you.

That said, if you really need to have js client side in boxwood, there's a bunch of ways you can do it. Given that the library is component oriented, ideally your components would keep the js they need.  Global js should be avoided, if possible.

Here's an example of an accordion. In modern html you can just use `details` and `section` to get pretty much the same result, so if you can create a component that relies just on html and css, that's the best option.

https://github.com/buxlabs/boxwood/blob/main/test/components/accordion/index.js

```js
const { component, css, div, js, h3 } = require("../../..")
const styles = css.load(__dirname, "index.css")

module.exports = component(
  ({ title }, children) => {
    return [
      h3({ class: styles.accordion }, title),
      div({ class: [styles.content, styles.hidden] }, children),
    ]
  },
  {
    styles,
    scripts: [
      js`
        const accordions = document.querySelector('.${styles.accordion}')
        accordions.forEach(accordion => {
          accordion.addEventListener('click', function () {
            const sibling = this.nextElement
            sibling.classList.toggle('${styles.content}')
          })
        })
      `,
    ],
  }
)
```

What happens here, is that the output page is going to include the js at the end of the `body` tag. The classes `styles.accordion` and `styles.content` are unique, so it should help you avoid collisions between components.

Pros:
- you can control everything
Cons:
- you need to control everything

This design approach gives you a lot of freedom while deciding on how to set up components. If you were to have a component that's being rendered 1000 times on a page you can change how event listeners are set up for better performance.

I hope this makes sense, please let me know if you have any other questions.
